export const meta = {
  name: 'veleiro-abas-base',
  description: 'Construção das abas Simulados, Glossário & Referências e Sobre/Contribuir (independentes da pesquisa)',
  phases: [{ title: 'Construção', detail: '3 construtores de abas' }],
}
const ROOT = '/home/sobranceiro/veleiro_certificacoes'
const SP = '/tmp/claude-1000/-home-sobranceiro/767d06b5-c8a6-4493-9ee3-da137f666222/scratchpad'
const COMMON = `Você é engenheiro front-end sênior e autor didático, construindo uma aba do app "Veleiro: de leigo a transatlântico" — app web estático, open source, PT-BR, comunitário (nada personalizado para uma pessoa), qualidade igual ou superior a RYA/ASA/NauticEd. Projeto: ${ROOT}. Hoje: 2026-10-07.
LEIA ANTES: ${ROOT}/PLAN.md (seções 1, 7, 10), ${ROOT}/docs/arquitetura.md (contrato obrigatório), ${ROOT}/docs/design-system.md, todos os arquivos de ${ROOT}/app/core/ (APIs prontas: VL.h, VL.store, VL.settings, VL.tabs.register, VL.quiz.*, VL.srs.*, VL.charts.*, VL.ui.*, VL.progress.*), ${ROOT}/app/assets/css/app.css e tokens.css, e o arquivo provisório da sua aba em app/tabs/.
REGRAS: script clássico (sem import/export, sem fetch local); só tokens CSS; CSS próprio da aba em app/assets/css/tabs/<aba>.css carregado com VL.loadCSS no render; PT-BR simples; sem CAIXA ALTA em rótulos, sem emojis, sem setas em botões; celular primeiro (360 px sem rolagem horizontal); acessível (foco, aria); tema claro e escuro; localStorage só via VL.store; limpeza com VL.aoSair. Fatos regulatórios só com referência verificável (fonte oficial + URL); se não puder confirmar, use VL.ui.seloQ(). Não edite app/core/ nem arquivos de outras abas; pedidos ao núcleo vão em core_requests.
TESTE NO NAVEGADOR (obrigatório, iterando): cd ${ROOT} && python3 tools/qa_shot.py --out ${SP}/aba-<rotulo> --wait 2000 <rotas> (e com --mobile --dark; --click "<seletor>" para interagir; --full). Abra os PNGs com Read e critique como designer; corrija até não haver pageerrors/console/overflowX.`
const RET = { type: 'object', properties: { arquivos: { type: 'array', items: { type: 'string' } }, rotas: { type: 'array', items: { type: 'string' } }, core_requests: { type: 'array', items: { type: 'string' } }, pendencias: { type: 'array', items: { type: 'string' } }, notas: { type: 'string' } }, required: ['arquivos', 'rotas', 'core_requests', 'pendencias', 'notas'] }

const JOBS = [
  { key: 'simulados', prompt: `SUA ABA: simulados (arquivo app/tabs/simulados.js, + app/tabs/simulados/*.js se quiser, + app/assets/css/tabs/simulados.css). Registre com id 'simulados', titulo 'Simulados e flashcards', curto 'Simulados', grupo 'ferramentas', icone 'prova', ordem 9.
DADOS (ainda serão produzidos por outra fase — seu código deve lidar com arquivo ausente mostrando estado vazio útil): bancos VL.carregarDado('questoes/arrais'|'questoes/mestre'|'questoes/capitao'|'questoes/vela'|'questoes/travessia'|'questoes/radio') → array de questões (formato em docs/arquitetura.md). Índice de baralhos: VL.carregarDado('flashcards/indice') → {decks:[{id, titulo, nivel, arquivo}]} e cada baralho VL.carregarDado(arquivo) → {id,titulo,nivel,cartas}.
FORMATO OFICIAL DAS PROVAS (NORMAM-211/DPC, Anexo 5-A, Seção I — fonte https://www.marinha.mil.br/sites/default/files/atos-normativos/dpc/normam/normam-211.pdf): Arrais-Amador 40 questões, duração máxima 2 h, aprovação com 5,0 de 10 (item 3 b-c); Mestre-Amador 40 questões de múltipla escolha, 4 com carta náutica, 3 h, 5,0 (item 2 c-d); Capitão-Amador 40 questões, 4 h, 5,0 (item 1 b-c), com 5 alternativas A–E nas provas publicadas. Mostre esses números com VL.ui.fonte('normas-98'), VL.ui.fonte('normas-99') (ARA), 'normas-92'/'normas-93' (MSA), 'normas-78'/'normas-79' (CPA) — ids de fatos de data/fontes.js (gerado depois; a função já lida com id ausente). Explique que as provas de Arrais e Mestre não são publicadas (são destruídas após a correção para proteger o banco de questões — fato 'normas-101') e que nosso banco é próprio, baseado no programa oficial; as do Capitão são publicadas pela DPC (link https://www.marinha.mil.br/dpc/exame-para-a-categoria-de-capitao-amador) e recomendamos praticá-las.
ROTAS: #/simulados — painel: para cada nível (Arrais, Mestre, Capitão; e "extras": Vela prática, Travessia, Rádio e segurança) mostrar nº de questões no banco, melhor nota e últimas tentativas, aproveitamento geral, e ações: "Prova no formato oficial", "Praticar por assunto", "Revisar as que errei", "Flashcards". Gráficos com VL.charts.criar (Chart.js): evolução das notas por nível ao longo do tempo (linha), aproveitamento por assunto do nível escolhido (barras horizontais, do mais fraco ao mais forte), dias de estudo (sequência atual via VL.progress.sequencia e um mapa de calor simples das últimas 12 semanas em SVG), previsão de revisões dos flashcards (barras 7 dias). #/simulados/<nivel> — página do nível: modos; filtro por assunto (chips com contagem e aproveitamento), quantidade (10/20/40), "só inéditas", "só as que errei". #/simulados/<nivel>/prova → VL.quiz.prova(el, {questoes: VL.quiz.sortear(banco, 40), minutos, notaMinima: 5, nivel, titulo}) com tela de instruções antes de começar (tempo, materiais permitidos na prova real: ARA caneta; MSA material de desenho; CPA régua paralela, compasso etc.). #/simulados/<nivel>/pratica?tema=…&n=… → VL.quiz.pratica. #/simulados/<nivel>/erradas → prática só com questões cujo último resultado foi erro (VL.progress.todasQuestaoStats()). #/simulados/flashcards — lista de baralhos por nível com VL.srs.stats (novas/devidas/maduras) e botão estudar; #/simulados/flashcards/<id> — se <id> for um nível (arrais, mestre, capitao, vela, travessia, radio), junte todos os baralhos desse nível num só (deck id = nível); se for id de baralho, só ele. Use VL.srs.mount.
Também: histórico de tentativas (tabela com data, modo, nota/acertos, duração) por nível. Tudo funcionando sem dados (estados vazios que explicam o que fazer). Para testar, crie DADOS TEMPORÁRIOS de teste em ${SP}/aba-simulados/ e copie para app/data/questoes/arrais.js e app/data/flashcards/indice.js + app/data/flashcards/teste.js SÓ durante o teste, e APAGUE essas cópias antes de terminar (confira com ls). Não deixe nenhuma questão de teste no app. RETOMADA: uma tentativa anterior desta tarefa caiu por falha de rede. Se seus arquivos já existem (app/tabs/simulados.js, app/tabs/simulados/*.js, app/data/glossario.js, app/assets/css/tabs/simulados.css) ou houver material em ${SP}/aba-simulados/, continue a partir deles em vez de recomeçar; termine, teste e corrija.` },

  { key: 'glossario', prompt: `SUA ABA: glossario (app/tabs/glossario.js + app/data/glossario.js + app/assets/css/tabs/glossario.css). Registre id 'glossario', titulo 'Glossário e referências', curto 'Glossário', grupo 'ferramentas', icone 'livro', ordem 10.
DADOS: escreva app/data/glossario.js com VL.dado('glossario', {termos:[{id (slug), termo, en (termo em inglês, opcional), def (HTML curto, 1–3 frases, para leigo), categoria, ver: [ids relacionados], figura?: {svg (inline, usando currentColor e var(--…) para funcionar nos dois temas)}, widget?: {w, opts} (para abrir um simulador relacionado)}]}) e logo depois VL.dado('glossarioIndice', {id: termo, …}). Meta: 250+ termos náuticos em PT-BR brasileiro correto, cobrindo: embarcação e casco (proa, popa, bombordo, boreste, través, alheta, bochecha, borda livre, calado, pontal, boca, comprimento, quilha, bolina, leme, cana do leme, roda de leme, costado, convés, cockpit, gaiúta, escotilha, vigia, balaústre, guarda-mancebo, púlpito, cunho, buzina, malagueta…), mastreação e velas (mastro, retranca, estai, estai de popa, brandal, enora, cruzeta, burro, adriça, escota, amantilho, vela grande, genoa, buja, balão/spinnaker, gennaker, valuma, testa, esteira, punho da adriça/amura/escota, garlindéu, tralha, rizo, catraca/winch, mordedor, moitão, patesca, carril…), manobra e mareação (orçar, arribar, cambar, jaibe, bordejar, bolina cerrada/folgada, través, largo, popa, caçar, folgar, panejar, capear, fundear, suspender, filame, atracar, amarrar, espringue, lançante, defensa, abatimento, deriva, seguimento…), navegação (rumo, marcação, rumo verdadeiro/magnético/da agulha, declinação, desvio, linha de posição, posição estimada, ponto, singradura, milha náutica, nó, latitude, longitude, carta náutica, isóbata, sondagem, nível de redução, preamar, baixa-mar, sizígia, quadratura, amplitude, enchente, vazante, estofo, corrente, ortodrômica, loxodrômica, derrota, waypoint, GNSS, radar, AIS, ecobatímetro, odômetro, agulha…), astronomia (sextante, altura, azimute, declinação do astro, ângulo horário, passagem meridiana, zênite, nadir, horizonte, almanaque, reta de altura, hora legal, fuso…), meteorologia (frente fria, ciclone extratropical, alísios, ZCIT, Beaufort, rajada, isóbara, barômetro, Buys-Ballot, nevoeiro, marulho, vaga…), segurança (colete, boia circular, balsa salva-vidas, EPIRB, PLB, SART, AIS-MOB, pirotécnicos, linha de vida, jackline, homem ao mar, hipotermia, extintor e classes de incêndio…), rádio (VHF, DSC, MMSI, canal 16, canal 70, MAYDAY, PAN-PAN, SÉCURITÉ, GMDSS, RENEC…), legislação (CHA, NORMAM, RLESTA, LESTA, RIPEAM, Capitania, Delegacia, Agência, NPCP, ETN, GRU, TIE, Aviso de Saída, NAVSEG, Arrais/Mestre/Capitão-Amador, Motonauta, Veleiro…). Ilustre ~30 termos-chave com SVG simples e preciso (partes do barco, pontos de vela, velas, direções relativas, marcas cardinais, nós remetendo ao widget 'nos'). Definições tecnicamente corretas — seja rigoroso (você será revisado por um instrutor cético).
ROTAS: #/glossario — busca instantânea sem acento/maiúsculas (por termo, sinônimo, inglês e texto da definição), filtro por categoria (chips), índice A–Z, lista densa e legível; #/glossario/termo/<id> — página do termo com definição, figura, relacionados, termo em inglês (só se VL.settings.get('intl')), e botão para o simulador relacionado; #/glossario/referencias — referências oficiais e de estudo, organizadas (Normas e legislação: NORMAM-211/DPC https://www.marinha.mil.br/sites/default/files/atos-normativos/dpc/normam/normam-211.pdf, NORMAM-212, página DPC Navegador Amador https://www.marinha.mil.br/dpc/navegador-amador, Normas da Autoridade Marítima https://www.marinha.mil.br/dpc/normas-autoridade-maritima-brasileira, provas de Capitão-Amador https://www.marinha.mil.br/dpc/exame-para-a-categoria-de-capitao-amador, Lei 9.537/1997 LESTA e Decreto 2.596/1998 RLESTA no planalto.gov.br; Cartas e publicações DHN/CHM: Tábuas das marés, Almanaque Náutico, Carta 12000, Lista de Faróis, Avisos aos Navegantes, livros "Navegação: a Ciência e a Arte" de Miguens; Meteorologia: CHM/Serviço Meteorológico Marinho, CPTEC/INPE, app Boletim ao Mar; Internacional (data-intl="on"): RYA, ASA, UNECE Resolução 40/ICC, World Sailing Offshore Special Regulations; Saúde: OMS International Medical Guide for Ships; Bibliografia recomendada pelo Anexo 5-A (liste os livros por categoria, conforme ${ROOT}/research/programa_provas.md seções 3.2, 5.1 e a do CPA). Cada link externo: CONFIRA que a URL abre hoje (curl -sL -o /dev/null -w "%{http_code}" -A "Mozilla/5.0"; para marinha.mil.br use o serviço local: curl -s -G localhost:8799/page --data-urlencode "url=<URL>" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('status'), d.get('title'))"). Mostre a data de consulta (2026-10-07). Se uma URL não abrir, troque pela página oficial correta ou remova. Use também os arquivos de ${ROOT}/research/*.md que já existirem (normas.md, programa_provas.md, conteudo_tecnico.md…) como fonte de URLs oficiais. RETOMADA: uma tentativa anterior desta tarefa caiu por falha de rede. Se seus arquivos já existem (app/tabs/glossario.js, app/tabs/glossario/*.js, app/data/glossario.js, app/assets/css/tabs/glossario.css) ou houver material em ${SP}/aba-glossario/, continue a partir deles em vez de recomeçar; termine, teste e corrija.` },

  { key: 'sobre', prompt: `SUA ABA: sobre (app/tabs/sobre.js + app/assets/css/tabs/sobre.css). Registre id 'sobre', titulo 'Sobre e contribuir', curto 'Sobre e contribuir', grupo 'projeto', icone 'coracao', ordem 11.
ROTAS: #/sobre — o que é o projeto (curso aberto e comunitário, PT-BR, do zero à travessia), para quem é, como foi feito (pesquisa em fontes oficiais com data de consulta; cada fato regulatório checado por dois verificadores independentes; o selo amarelo "a confirmar" — mostre um exemplo com VL.ui.seloQ() — significa divergência entre fontes ou falta de fonte oficial), AVISO LEGAL E DE SEGURANÇA bem visível (não substitui instrução prática com instrutor habilitado nem a habilitação oficial da Marinha; confirme regras/taxas/datas na Capitania antes da prova; cartas e dados de treinamento não servem para navegação; o projeto não é oficial nem tem vínculo com a Marinha do Brasil), privacidade (tudo fica no navegador; sem rastreadores, sem cadastro; geolocalização opcional só para "perto de mim"; backup do progresso em arquivo via VL.progress.exportarArquivo/importarArquivo e botão para Configurações VL.config.abrir()), como contribuir (relatar erro: o que incluir; sugerir local de prática com URL; propor questão; regras: fato regulatório só com fonte oficial + URL + data; nada inventado; estrutura do repositório: app/, research/, docs/, tools/; rodar node tools/validate.mjs e tools/qa_shot.py; código MIT e conteúdo CC BY-SA 4.0 — explique em linguagem simples o que isso permite), créditos e licenças de terceiros (three.js MIT, Leaflet BSD-2, Chart.js MIT, D3 ISC, fonte Atkinson Hyperlegible Next OFL — Braille Institute, Natural Earth domínio público, IBGE malhas, OpenStreetMap ODbL quando online) — leia ${ROOT}/app/assets/vendor/LICENSES.md, versão do app (VL.versao).
#/sobre/fontes — "Fatos verificados": lista TODOS os fatos de VL.data.fontes.fatos (arquivo data/fontes.js, já carregado no index; formato em docs/arquitetura.md; hoje pode estar vazio — trate), agrupados por tópico (campo topico: normas, programa, taxas, radio, internacional, travessia, tecnico, benchmark), com busca, filtro "só a confirmar", e para cada fato: afirmação, link da fonte com localizador, data de consulta e, se a confirmar, a nota do verificador. Isso dá transparência total à comunidade.
#/sobre/licencas — textos curtos das licenças com links (LICENSE e LICENSE-CONTEUDO.txt ficam na raiz do repositório, fora de app/ — então use links para https://opensource.org/license/mit e https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br e explique onde estão no repositório).
Escreva bem: tom direto e acolhedor, sem marketing.` },
]
phase('Construção')
const r = await parallel(JOBS.map(j => () => agent(COMMON + '\n\n' + j.prompt + `\n\nRótulo da pasta temporária: ${j.key}.`, { label: `aba:${j.key}`, phase: 'Construção', schema: RET })))
return r.map((x, i) => x ? { key: JOBS[i].key, ...x } : { key: JOBS[i].key, failed: true })