export const meta = {
  name: 'veleiro-qa-revisao',
  description: 'QA no navegador por área (donos de arquivos) + revisão técnica por instrutor de vela cético por curso, com correções',
  phases: [{ title: 'QA', detail: '5 testadores no navegador' }, { title: 'Revisão técnica', detail: '6 instrutores céticos, um por curso' }],
}
const ROOT = '/home/sobranceiro/veleiro_certificacoes'
const SP = '/tmp/claude-1000/-home-sobranceiro/767d06b5-c8a6-4493-9ee3-da137f666222/scratchpad'
const BASE = `Projeto "Veleiro: de leigo a transatlântico" em ${ROOT} — app web estático, offline, PT-BR, comunitário (PLAN.md é o contrato; seção 7 e 10 = critérios de pronto). Leia ${ROOT}/docs/arquitetura.md e ${ROOT}/docs/design-system.md. Ferramenta de teste: cd ${ROOT} && python3 tools/qa_shot.py --out ${SP}/qa-<rótulo> [--mobile] [--dark] [--offline] [--full] [--click "<seletor playwright>"] [--wait ms] <rota> … (imprime JSON com console/pageerrors/externas/overflowX e salva PNG; abra PNGs com Read só quando precisar ver layout — no máximo 8 imagens). Para fluxos com várias interações, escreva um script Playwright próprio em ${SP}/qa-<rótulo>/ (Chrome do sistema: channel="chrome", headless) baseado em tools/qa_shot.py. Validação de dados: node tools/validate.mjs. Depois de mudar dados: python3 tools/build_manifesto.py. Só edite os arquivos que são SEUS (listados); problemas fora deles vão no relatório com arquivo, rota e correção sugerida.`
const RET = { type: 'object', properties: { relatorio: { type: 'string' }, corrigidos: { type: 'array', items: { type: 'string' } }, pendentes: { type: 'array', items: { type: 'object', properties: { arquivo: { type: 'string' }, problema: { type: 'string' }, sugestao: { type: 'string' }, gravidade: { type: 'string', enum: ['alta', 'media', 'baixa'] } }, required: ['arquivo', 'problema', 'gravidade'] } }, notas: { type: 'string' } }, required: ['relatorio', 'corrigidos', 'pendentes', 'notas'] }

const QA = [
  { k: 'nucleo', p: `ÁREA: núcleo, moldura e critérios globais. SEUS ARQUIVOS: app/core/*, app/index.html, app/assets/css/app.css, app/assets/css/tokens.css, run.sh, README.md. Teste: (1) TODAS as 10 abas + Sobre (roteiro, arrais, mestre, capitao, vela, travessia, radio, locais, simulados, glossario, sobre) em desktop claro, celular escuro e --offline: zero pageerrors/console/externas, overflowX false; (2) boas-vindas (use --fresh e --click) com os 4 passos, UF/cidade/ritmo opcionais, trilha internacional LIGADA por padrão; desligar a trilha em Configurações deve esconder conteúdo intl (data-intl="on") em cursos, glossário e locais — confira em pelo menos 3 páginas; (3) tema auto/claro/escuro pelo botão e por Configurações; (4) gaveta de navegação no celular (abrir/fechar, Esc, foco); (5) backup exportar/importar e apagar progresso; (6) prova cronometrada: protegerSaida pede confirmação ao trocar de aba; (7) marcar lição como concluída atualiza o medidor do curso no trilho; (8) ./run.sh --check e ./run.sh sobem sem erro (teste o servidor com curl em 127.0.0.1 e depois mate o processo); (9) acessibilidade básica: foco visível, aria-label nos botões só com ícone, contraste. Corrija o que for seu. Escreva ${ROOT}/docs/qa/nucleo.md.` },
  { k: 'roteiro-locais', p: `ÁREA: abas Roteiro e Onde estudar. SEUS ARQUIVOS: app/tabs/roteiro.js, app/tabs/roteiro/*, app/data/roteiro.js, app/assets/css/tabs/roteiro.css, app/tabs/locais.js, app/tabs/locais/*, app/assets/css/tabs/locais.css. Roteiro: a derrota-carta (elemento memorável) legível em desktop e celular, clique em cada waypoint (#/roteiro/<etapa>), checkboxes persistem, linha do tempo recalcula com o ritmo, "como agendar em qualquer Capitania" com a Capitania mais próxima quando há UF configurada, custos só oficiais (com selo) ou faixa de preços públicos verificados; nada inventado. Locais: mapa offline sem NENHUMA requisição externa por padrão (--offline: externas []), camada OSM só se ligada, filtros por UF/tipo/curso/busca, "perto de mim" via base configurada (simule setando localStorage 'veleiro.v1.settings' com uf:'PB'), lista sincronizada, popups com site e data de verificação, trilha intl desligada esconde escolas RYA/ASA; contagem ≥ 60 locais fora Capitanias. Corrija o que for seu. Escreva ${ROOT}/docs/qa/roteiro-locais.md.` },
  { k: 'ferramentas', p: `ÁREA: Simulados, Glossário e Sobre. SEUS ARQUIVOS: app/tabs/simulados.js e app/tabs/simulados/*, app/tabs/glossario.js e app/tabs/glossario/*, app/tabs/sobre.js, app/assets/css/tabs/{simulados,glossario,sobre}.css. Agora existem os bancos reais (data/questoes/*.js) e os baralhos (data/flashcards/indice.js + 15 baralhos). Teste de ponta a ponta: prova oficial de cada nível (40 questões, tempo ARA 2h/MSA 3h/CPA 4h, 4 de carta no Mestre), entregar, correção comentada, gráficos de progresso (Chart.js) aparecendo com dados após 2 tentativas, prática por assunto, revisar erradas, flashcards por nível (repetição espaçada: avaliar cartas, voltar e ver contagens mudarem), glossário (busca sem acento, termo, referências), Sobre/fontes com os 1.4 mil fatos (filtro só a confirmar), licenças. Corrija o que for seu. Escreva ${ROOT}/docs/qa/ferramentas.md.` },
  { k: 'widgets-a', p: `ÁREA: widgets ripeam-luzes, sinais-sonoros, regras-governo, boias-iala, ritmos-luz, nos, carta-nautica, agulha-calc, mares, sextante, reta-altura. SEUS ARQUIVOS: app/widgets/<esses>.js e app/assets/css/widgets/<esses>.css. Para cada um (#/lab/<nome>): desktop claro + celular escuro + --offline, interações principais (modo explorar e desafio), texto legível no celular (≥ 12 px), sem sobreposição, limpeza ao sair. Confira também a correção técnica do que é exibido (luzes e setores do RIPEAM, IALA B, ritmos, cálculos de agulha/marés/astro com 2 exemplos feitos à mão). Corrija o que for seu. Escreva ${ROOT}/docs/qa/widgets-a.md.` },
  { k: 'widgets-b', p: `ÁREA: widgets esfera-celeste, globo-rotas, derrota-calc, veleiro-3d, mareacao, manobras, meteo-sinotica, beaufort, quartos, provisoes, vhf-sim, alfabeto-fonetico. SEUS ARQUIVOS: app/widgets/<esses>.js e app/assets/css/widgets/<esses>.css. Para cada um (#/lab/<nome>): desktop claro + celular escuro + --offline, interações principais, legibilidade no celular, 3D com fallback se WebGL falhar, limpeza ao sair. Confira a correção técnica (ortodrômica x loxodrômica com 1 exemplo à mão, giro do vento no Hemisfério Sul, Beaufort, procedimento MAYDAY, alfabeto da UIT). Corrija o que for seu. Escreva ${ROOT}/docs/qa/widgets-b.md.` },
]
const CURSOS = ['arrais', 'mestre', 'capitao', 'vela', 'travessia', 'radio']
const REV = c => `Você é um INSTRUTOR DE VELA E NAVEGAÇÃO CÉTICO (Capitão-Amador, Yachtmaster Ocean, 30 anos de mar) fazendo a revisão técnica final do curso "${c}". SEUS ARQUIVOS: app/data/cursos/${c}-*.js e app/data/flashcards/${c}-*.js (e research/_work/questoes/${c}-*.rev2.json para correções no banco; depois rode python3 tools/build_questoes.py). Leia TODAS as lições e procure ERROS TÉCNICOS: regra do RIPEAM com número/parágrafo errado, balizamento fora da Região B, conta errada (refaça), conversão de rumos com sinal errado, física errada em figura SVG (ex.: em arrais m14 l1 o centro de carena B está do lado errado do barco adernado — corrija), terminologia náutica brasileira errada, conselho de segurança perigoso, fato regulatório escrito sem bloco fato/ref, texto que contradiz um fato verificado (confira em research/claims_verified.json — fatos com status "a confirmar" e nota de "divergente" exigem que o texto siga a correção ou fique cauteloso), widget com opts inexistentes (confira docs/widgets.md). Leia também 40 questões sorteadas do banco do nível (app/data/questoes/${c}.js) procurando gabarito errado. Corrija diretamente tudo que for seu, mantendo o JavaScript válido (valide com node após cada arquivo) e sem reescrever o que está certo. Abra 2 lições no navegador para conferir que nada quebrou. Escreva ${ROOT}/docs/revisao/${c}.md com a lista de erros encontrados, o que corrigiu e o que ficou pendente.`

phase('QA')
const q = parallel(QA.map(x => () => agent(BASE + '\n\n' + x.p, { label: `qa:${x.k}`, phase: 'QA', schema: RET, model: 'sonnet' }).then(r => r && { area: x.k, ...r })))
const r = parallel(CURSOS.map(c => () => agent(BASE + '\n\n' + REV(c), { label: `revisao:${c}`, phase: 'Revisão técnica', schema: RET, model: 'sonnet' }).then(x => x && { curso: c, ...x })))
const [a, b] = await Promise.all([q, r])
return { qa: a.map(x => x && { area: x.area, corrigidos: x.corrigidos.length, pendentes: x.pendentes }), revisao: b.map(x => x && { curso: x.curso, corrigidos: x.corrigidos.length, pendentes: x.pendentes }) }
