export const meta = {
  name: 'veleiro-widgets-2',
  description: 'Construção paralela dos simuladores/visualizações (RIPEAM, balizamento, nós, carta, astro, globo, veleiro 3D, meteo, rádio) com teste no navegador',
  phases: [
    { title: 'Construção', detail: '9 construtores de widgets, cada um com seus arquivos' },
  ],
}

const ROOT = '/home/sobranceiro/veleiro_certificacoes'
const SP = '/tmp/claude-1000/-home-sobranceiro/767d06b5-c8a6-4493-9ee3-da137f666222/scratchpad'

const COMMON = `Você é um engenheiro front-end sênior e instrutor de vela, construindo simuladores interativos para o app "Veleiro: de leigo a transatlântico" — app web estático, open source, PT-BR, para a comunidade brasileira, com qualidade IGUAL OU SUPERIOR a RYA Interactive / NauticEd / ASA. Projeto: ${ROOT}. Hoje: 2026-10-07.

ANTES DE CODAR, leia: ${ROOT}/docs/arquitetura.md (contrato — obrigatório), ${ROOT}/docs/design-system.md, ${ROOT}/app/core/vl.js, ${ROOT}/app/core/ui.js, ${ROOT}/app/assets/css/tokens.css e ${ROOT}/app/assets/css/app.css (classes prontas: .instrumento via VL.ui.instrumento(), .btn, .segmented, .chip, .switch, .callout, .tabela, .cena-3d, .svg-interativo…).

REGRAS DURAS:
- Sem módulos ES, sem fetch de arquivos locais: cada widget é um script clássico widgets/<nome>.js que chama VL.widgets.define('<nome>', { css?: ['assets/css/widgets/<nome>.css'], mount(el, opts) { …; return limpeza } }). Three.js via VL.libs.three() (window.THREE já inclui OrbitControls, CSS2DRenderer, CSS2DObject, RoundedBoxGeometry, mergeVertices); D3 via VL.libs.d3(); geografia offline em VL.carregarDado? NÃO — geografia: VL.load('data/geo/world_land_110m.js') define VL.geo.land110m (GeoJSON), 'data/geo/world_land_50m.js' → VL.geo.land50m, 'data/geo/br_uf.js' → VL.geo.brUF.
- Pode haver mais de uma instância do widget na mesma página: nada de IDs globais fixos; escopo tudo dentro de el. Devolva função de limpeza (pare requestAnimationFrame, timers, AudioContext, ResizeObserver, IntersectionObserver, listeners globais; dispose() em geometrias/materiais/texturas/renderer do Three.js).
- Visual: use SOMENTE tokens CSS (var(--ink), --paper, --shoal, --shoal-2, --line, --land, --magenta, --ok, --erro, --aviso, --sea-1/2/3) e, para luzes/boias, --nav-red, --nav-green, --nav-white, --nav-yellow. Em canvas/WebGL leia as cores com VL.cssVar('--x') e redesenhe em VL.on('tema', …) (devolve função para desinscrever — chame na limpeza). Os dois temas (claro "Carta", escuro "Quarto de vigia") devem ficar bonitos. Simuladores ficam dentro de VL.ui.instrumento({titulo}). Sem CAIXA ALTA em rótulos, sem emojis, sem setas "→" em botões. Movimento só quando explica algo; respeite prefers-reduced-motion (ofereça passo a passo manual).
- Celular primeiro: funciona em 360 px sem rolagem horizontal; toque com pointer events (arrastar, pinça quando fizer sentido); alvos ≥ 40 px. Teclado e aria-label nos controles.
- Three.js: renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); ResizeObserver; pause o loop fora da tela (IntersectionObserver); fallback com mensagem se WebGL falhar.
- PT-BR simples para leigos, termos náuticos brasileiros corretos (bombordo/boreste, proa/popa, orçar/arribar, cambar, jaibe/jibe, rizar, capear, marcação, rumo verdadeiro/magnético/da agulha, declinação magnética, desvio da agulha, preamar/baixa-mar, etc.). Quando a trilha internacional estiver ligada (VL.settings.get('intl')), pode mostrar o termo em inglês entre parênteses.
- PRECISÃO TÉCNICA é inegociável: siga o RIPEAM-72/COLREG (regras e Anexos), o Sistema de Balizamento IALA Região B (adotado no Brasil), as fórmulas de navegação/astronomia corretas. Mostre na interface a regra/fonte usada (ex.: "RIPEAM, Regra 21"). Se algo depende de norma nacional que você não pode verificar, marque com VL.ui.seloQ() e explique. Nada inventado.
- Cada widget deve ter: modo explorar (manipular livremente) E modo exercício/desafio com feedback explicado, quando fizer sentido pedagogicamente.
- Só crie/edite os arquivos atribuídos a você (widgets/<seus nomes>.js e assets/css/widgets/<seus nomes>.css). NÃO edite app/core/, app/index.html, nem arquivos de outros. Se precisar de algo no núcleo, descreva em core_requests.

TESTE NO NAVEGADOR (obrigatório, iterar até ficar bom): a rota oculta #/lab/<nome>?opts=<json url-encoded> monta o widget. Rode, por exemplo:
  cd ${ROOT} && python3 tools/qa_shot.py --out ${SP}/w-<rotulo> --wait 2500 "lab/<nome>"
  python3 tools/qa_shot.py --out ${SP}/w-<rotulo> --mobile --dark --wait 2500 "lab/<nome>"
  (--click "<seletor playwright>" para interagir antes da captura; --full para página inteira; --offline para garantir zero rede.)
Ele imprime JSON com console/pageerrors/externas/overflowX e salva PNG — ABRA os PNGs com a ferramenta Read e critique como designer e como instrutor; corrija até: pageerrors [], console [], externas [] (offline), overflowX false no celular, visual nítido e legível nos dois temas. Para lógica pura, você pode também testar com node (extraindo funções) se ajudar.
Pasta temporária: ${SP}/w-<rotulo>/.`

const RET = {
  type: 'object',
  properties: {
    widgets: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          nome: { type: 'string' },
          arquivo: { type: 'string' },
          descricao: { type: 'string' },
          opts: { type: 'string', description: 'opções aceitas por mount(el, opts), com valores padrão' },
          exemplo_bloco: { type: 'string', description: 'JSON de um bloco de lição que usa o widget, ex. {"t":"widget","w":"nos","opts":{"no":"lais-de-guia"}}' },
          regras_citadas: { type: 'string' },
          screenshots: { type: 'array', items: { type: 'string' } },
          limitacoes: { type: 'string' },
        },
        required: ['nome', 'arquivo', 'descricao', 'opts', 'exemplo_bloco', 'screenshots', 'limitacoes'],
      },
    },
    arquivos: { type: 'array', items: { type: 'string' } },
    core_requests: { type: 'array', items: { type: 'string' } },
    notas: { type: 'string' },
  },
  required: ['widgets', 'arquivos', 'core_requests', 'notas'],
}

const JOBS = [
  { key: 'ripeam', prompt: `SEUS WIDGETS: ripeam-luzes, sinais-sonoros, regras-governo.
1) ripeam-luzes — simulador noturno de luzes e marcas (RIPEAM Regras 20–31 + Anexo I). Cena noturna (SVG ou canvas) vista do nosso barco: a outra embarcação aparece só pelas luzes (com halo), sobre mar escuro e horizonte; opcional silhueta tênue. Controles: tipo/situação da embarcação — propulsão mecânica <50 m (1 mastro) e ≥50 m (2 mastros), <12 m (opção de luz circular branca + bordos), veleiro em navegação (bordos + alcançado; opção lanterna tricolor no topo para <20 m; opção luzes circulares vermelha sobre verde no mastro), embarcação a vela também a motor (marca cone de vértice para baixo de dia), pesca de arrasto (verde sobre branco), pesca não-arrasto (vermelho sobre branco), sem governo (2 vermelhas circulares), manobrabilidade restrita (vermelha-branca-vermelha), restrita pelo calado (3 vermelhas), reboque (2 ou 3 luzes de mastro + luz de reboque amarela; comprimento do reboque >200 m), praticagem (branca sobre vermelha), fundeada (<50 m: 1 branca circular; ≥50 m: 2), encalhada, embarcação a remo/<7 m e <7 nós, hovercraft (amarela intermitente). Slider de aspecto (marcação relativa de onde vemos o alvo, 0–360°) que calcula quais luzes ficam visíveis pelos setores corretos (mastro 225°, bordos 112,5° cada, alcançado 135°, circulares 360°) e posição vertical/horizontal correta. Alternância dia/noite para marcas diurnas (bola, cilindro, cone(s), losango, cones opostos). Modo desafio: configuração sorteada → o aluno identifica o tipo e para onde a embarcação está indo/qual bordo vê, com explicação e regra citada. Painel lateral: nome da situação, regra, explicação curta.
2) sinais-sonoros — RIPEAM Regras 32–37: Web Audio API (sons sintetizados: apito curto ≈1 s, longo 4–6 s; sino; gongo) com linha do tempo visual. Regra 34 (sinais de manobra e advertência: 1 curto boreste, 2 curtos bombordo, 3 curtos máquinas a ré, 5+ curtos dúvida/perigo, ultrapassagem em canal estreito 2 longos+1 curto / 2 longos+2 curtos / resposta longo-curto-longo-curto, curva/obstáculo 1 longo), Regra 35 (visibilidade restrita: 1 longo a cada ≤2 min propulsão mecânica com seguimento; 2 longos parada; longo+2 curtos para vela/pesca/sem governo/manobrabilidade restrita/calado/rebocador; longo+3 curtos rebocado; fundeada: sino rápido 5 s a cada ≤1 min, ≥100 m sino a vante + gongo a ré, opcional curto-longo-curto; encalhada: 3 badaladas distintas + sino + 3 badaladas), Regra 37/Anexo IV sinais de perigo. Botão "acelerar tempo" para os intervalos de 2 min. Modo desafio: ouvir e identificar. Áudio só começa após clique do usuário; volume e silenciar.
3) regras-governo — Regras 8, 12–18: cenas de encontro em vista de cima (SVG) com duas embarcações, rumos e (para veleiros) vento; o aluno identifica a situação (roda a roda, rumos cruzados, ultrapassagem, veleiros com vento em bordos diferentes/mesmo bordo barlavento-sotavento) e quem manobra/quem mantém rumo e velocidade, e qual ação correta (ex.: guinar para boreste). Gerador de cenários aleatórios + explicação com regra; modo explorar arrastando o rumo dos barcos e a direção do vento, com o veredito atualizando ao vivo. Inclua a hierarquia da Regra 18 e o setor de ultrapassagem (mais de 22,5° por ante a ré do través).` },

  { key: 'balizamento', prompt: `SEUS WIDGETS: boias-iala, ritmos-luz.
1) boias-iala — Sistema de Balizamento Marítimo IALA REGIÃO B (o do Brasil): galeria com cada marca em 3D (Three.js, formas procedurais: cilíndrica/lata, cônica, pilar, charuto/spar, esférica, com marcas de tope corretas) e também em SVG leve para lista: laterais de bombordo (verde, cilíndrica, tope cilindro verde, luz verde) e boreste (vermelha, cônica, tope cone vermelho, luz vermelha) — lembrando que na Região B, entrando do mar, deixa-se o VERMELHO a BORESTE; canal preferencial (laterais modificadas: faixa horizontal da outra cor, ritmo Fl(2+1)); cardinais N/L/S/O (preto/amarelo nas posições corretas, topes de dois cones, luzes branca Q/VQ: N contínua, L Q(3) 10s / VQ(3) 5s, S Q(6)+LFl 15s / VQ(6)+LFl 10s, O Q(9) 15s / VQ(9) 10s); perigo isolado (preto com faixa vermelha, 2 esferas pretas, Fl(2) branca); águas seguras (listras verticais vermelhas e brancas, 1 esfera vermelha, Iso/Oc/LFl 10s/Mo(A) branca); especial (amarela, X amarelo, luz amarela); marca de perigo novo/naufrágio (azul/amarelo listras verticais, cruz amarela vertical, luz alternada Al Bu Y). Clique numa marca → ficha (nome, significado, por onde passar, cores, forma, tope, luz com animação do ritmo, regra/IALA). Modo "entrando no porto": mapa SVG de um canal com boias; o aluno decide por qual lado passar de cada uma / arrasta o barco pelo canal correto; feedback. Modo desafio: identificar marcas sorteadas (também de noite, só pela luz). Indique a fonte (IALA Maritime Buoyage System, Região B; DHN/Marinha) e cite que o Brasil adota a Região B.
2) ritmos-luz — decodificador de característica de luz: escolha ou digite (ex.: "Fl(3) W 15s 12M", "Oc R 4s", "Iso G 6s", "Q(6)+LFl W 15s", "Mo(A) W 8s", "Al WR 6s", "LFl G 10s", "VQ(9) W 10s") → lâmpada animada em tempo real + linha do tempo do período com luz/eclipse desenhados + explicação de cada abreviatura (F, Fl, LFl, Oc, Iso, Q, VQ, UQ, Mo, Al, Dir, período, cor, alcance em milhas). Use nomes em português (lampejo, lampejo longo, ocultação, isofase, rápida, muito rápida, código Morse, alternada) com a abreviatura internacional usada nas cartas e Lista de Faróis. Parser robusto para os formatos comuns. Modo desafio: ver piscar e escolher a característica correta.` },

  { key: 'nos', prompt: `SEU WIDGET: nos — nós e voltas animados passo a passo (SVG). Conjunto mínimo (com nome brasileiro + inglês se intl): lais de guia (bowline), nó de oito (figure-eight stopper), nó direito (reef knot) — com o aviso do nó torto/“de vaca” (granny), volta do fiel (clove hitch), volta redonda e dois cotes (round turn and two half hitches), nó de escota singelo e dobrado (sheet bend / double sheet bend), volta de cunho/cunho (cleat hitch), volta de fiador em mosquetão? (só se tiver certeza) e lais de guia de correr ou nó de correr apenas se correto. Para cada nó: para que serve a bordo, vantagens, cuidados, e 5–10 etapas animadas mostrando o cabo sendo passado (o "chicote" se movendo), com cruzamentos POR CIMA/POR BAIXO desenhados corretamente (cabo com contorno e sombra, segmentos em ordem de profundidade, ou gaps nos cruzamentos por baixo) — o aluno tem que conseguir reproduzir o nó com um cabo real seguindo a animação. Duas cores de cabo quando o nó une dois cabos. Controles: tocar/pausar, etapa anterior/próxima, velocidade, repetir, e texto da etapa ("Faça uma pequena alça (o 'buraco do coelho')…"). Respeite prefers-reduced-motion (sem animação automática; etapas manuais). Lista/galeria de nós com miniatura do nó pronto; opts.no para abrir um nó específico. Modo desafio: "qual nó usar para…?" (ex.: amarrar a escota na vela de proa, fazer uma alça que não corre para resgatar alguém, prender a defensa ao balaústre, impedir que a ponta escape do moitão). Desenhe com cuidado: este é o item em que materiais ruins mais falham — revise cada nó nas capturas, com zoom, e compare mentalmente com o nó real.` },

  { key: 'navegacao', prompt: `SEUS WIDGETS: carta-nautica, agulha-calc, mares.
1) carta-nautica — carta náutica interativa (SVG, pan/zoom com mouse/toque e pinça) de uma costa FICTÍCIA mas realista (diga "carta de treinamento — não use para navegação"), no estilo DHN: terra em --land, isóbatas (5, 10, 20, 50 m) com tintas de azul, sondagens em itálico, faróis com característica (ex.: "Fl(2) W 10s 15M"), boias IALA B, perigos (pedras, naufrágio), escala de latitude/longitude nas bordas (minutos e décimos), rosa dos ventos com anel verdadeiro e magnético e a anotação de declinação (ex.: "Dec 21°40'W (2025), variação anual 8'W"). Ferramentas: (a) régua paralela/transferidor: traçar rumo e ler o rumo verdadeiro; (b) compasso de pontas secas: medir distância na escala de latitude (1' = 1 milha náutica); (c) plotar posição por coordenadas; (d) marcações a pontos notáveis → linha de posição; posição por duas/três marcações (com "chapéu de bicão"/triângulo de erro); (e) navegação estimada (posição estimada por rumo, velocidade e tempo); (f) triângulo de corrente: rumo na superfície x rumo no fundo, corrente (direção/força), abatimento por vento; (g) marcações sucessivas (ex.: dobrar a marcação na proa / 45° e través) se possível. Modo exercício com problemas gerados (com tolerância de ±2° e ±0,2 M) e correção explicada passo a passo; modo livre. Tudo responsivo; no celular, ferramentas em uma barra compacta.
2) agulha-calc — conversão de rumos e marcações: verdadeiro (Rv), magnético (Rm), da agulha (Rag); declinação magnética (dmg, E/W — atualização anual a partir do ano da carta) e desvio da agulha (Dsv, E/W, pela curva/tabela de desvios para o rumo da agulha). Mostre a cadeia Rv ⇄ Rm ⇄ Rag com a convenção de sinais usada no Brasil (verifique em "Navegação: a Ciência e a Arte", Miguens/DHN: Rv = Rm + dmg, Rm = Rag + Dsv, com E positivo e W negativo) e um mnemônico; tabela de desvios exemplo com interpolação; exercícios aleatórios (incluindo marcações e atualização da declinação pelo ano) com resolução comentada.
3) mares — marés: tábua de marés de EXEMPLO no formato da DHN (horas e alturas de preamar e baixa-mar, nível de redução; deixe claro que é exemplo e linke para a Tábua oficial da DHN/CHM — https://www.marinha.mil.br/chm/tabuas-de-mare), curva de maré (cossenoidal) desenhada, cálculo da altura num horário pela regra dos doze avos (1-2-3-3-2-1) e pelo método do cosseno, comparação dos dois; altura de maré necessária / folga abaixo da quilha (profundidade da carta + altura da maré − calado); horário em que dá para passar num baixio; sizígia x quadratura explicadas com Lua/Sol num mini-diagrama. Exercícios com correção.` },

  { key: 'astro', prompt: `SEUS WIDGETS: esfera-celeste, sextante, reta-altura.
1) esfera-celeste — Three.js: esfera celeste vista de fora e/ou do observador; latitude do observador (slider −60°…+60°; padrões Brasil), horizonte (plano translúcido), zênite/nadir, polos celestes, equador celeste, meridiano do observador, eclíptica; o Sol num dia escolhido (declinação calculada pela data com fórmula padrão de precisão ~0,5°) e seu arco diurno; ~20 estrelas brilhantes de navegação com coordenadas J2000 corretas (AR/Dec — ex.: Sirius, Canopus, Arcturus, Vega, Capella, Rigel, Procyon, Achernar, Betelgeuse, Hadar, Altair, Acrux, Aldebaran, Antares, Spica, Pollux, Fomalhaut, Deneb, Regulus, Polaris) e o Cruzeiro do Sul; tempo animável (hora sideral) para ver o céu girar; ao clicar num astro mostrar declinação, ângulo horário local (AHL) e Greenwich (AHG) para uma longitude escolhida, altura (a) e azimute (Az) calculados — e o triângulo de posição (Polo-Zênite-Astro) desenhado. Texto curto explicando cada elemento. Rótulos com CSS2DRenderer.
2) sextante — Three.js: modelo procedural de sextante (arco graduado, alidade/braço de índice, espelho grande e pequeno, luneta, filtros, tambor micrométrico) que o aluno gira; partes clicáveis com nomes. Simulação da observação do Sol: visão pela luneta (canvas 2D) com horizonte e imagem refletida do Sol; o aluno move a alidade/tambor até o limbo inferior tangenciar o horizonte ("balançar o sextante"); leitura Hi (altura instrumental) em graus e minutos. Depois correções: erro instrumental (índice), depressão do horizonte (dip ≈ 1,76'·√(altura do olho em m)), refração (fórmula de Bennett), semidiâmetro (≈16'), paralaxe (pequena para o Sol) → altura verdadeira (Ho). Explique cada correção. Modo exercício.
3) reta-altura — navegação astronômica de cálculo: (a) método de Marcq Saint-Hilaire: entradas posição estimada (lat/long), AHG e declinação do astro (do Almanaque — permita digitar), Ho; calcula AHL, altura calculada (Hc) por sen Hc = sen φ sen δ + cos φ cos δ cos AHL e azimute, diferença de alturas Δa = Ho − Hc ("para o astro" se positiva), e plota a reta de altura numa folha de plotagem SVG (posição estimada, azimute, intercepto, reta perpendicular); duas ou três retas → posição observada. (b) latitude pela passagem meridiana do Sol (regras de sinal claras: φ = 90° − Ho ± δ conforme o astro passe ao norte/sul) e (c) cálculo da hora legal aproximada da passagem meridiana superior do Sol (HML da PMS ≈ 12h ± equação do tempo do almanaque; converter longitude em tempo; fuso) — o programa oficial do Capitão-Amador cobra (b) e (c). Passo a passo mostrado com números, exercícios gerados com correção. Diga que os dados de almanaque usados nos exercícios são simulados/aproximados e indique o Almanaque Náutico da DHN como fonte oficial.` },

  { key: 'globo', prompt: `SEUS WIDGETS: globo-rotas, derrota-calc.
1) globo-rotas — Three.js: globo da Terra com continentes desenhados em canvas a partir de VL.geo.land110m (equirretangular → textura; cores dos tokens --land e --sea-*; refaça a textura ao trocar tema), graticulado a cada 10°/30°, Equador e trópicos. Rotas: (a) ortodrômica (círculo máximo) x loxodrômica (rumo constante) entre dois pontos escolhidos por presets ou clicando no globo — distância de cada uma em milhas náuticas, rumo inicial, rumo constante, diferença em milhas e %; vértice da ortodrômica. (b) presets de travessias: Salvador → Mindelo (Cabo Verde), Recife → Fernando de Noronha, Natal → Mindelo, Las Palmas de Gran Canaria → Rodney Bay, Santa Lúcia (rota da ARC), Mindelo → Granada?/Caribe, Rio de Janeiro → Cidade do Cabo (e a inversa), Caribe → Bermudas → Açores → Lisboa (retorno), Salvador → Caribe pela costa. Animação de um barquinho ao longo da rota (com pausa). (c) camada esquemática de ventos alísios e ZCIT (marcada como "esquemático — use Pilot Charts reais para planejar"). Rotação com OrbitControls, zoom, toque; pausa de animação fora da tela. Nomes de oceanos e mares em itálico (convenção da carta).
2) derrota-calc — calculadora passo a passo: ortodrômica (distância por cos d = sen φ1 sen φ2 + cos φ1 cos φ2 cos Δλ, rumo inicial, vértice) e loxodrômica (latitudes crescidas/Mercator: rumo e distância), comparação; navegação plana (estimada) para pequenas distâncias (apartamento, diferença de latitude); conversões (graus-minutos-décimos, milhas, nós, tempo de viagem a X nós). Entradas validadas, mensagens claras, exemplos prontos (mesmos presets) e exercícios com correção.` },

  { key: 'veleiro', prompt: `SEUS WIDGETS: veleiro-3d, mareacao, manobras.
1) veleiro-3d — Three.js: veleiro de cruzeiro de ~32 pés (≈9,75 m), sloop, procedural e bonito: casco com linhas suaves (loft/lathe com seção em V suave e popa transom), convés, cabine, cockpit com roda de leme ou cana (opção), quilha de bolina fixa (fin keel), leme suspenso (spade), mastro (~13–14 m acima do convés), retranca, estai de proa, estai de popa (backstay), brandais e enoras/cruzetas, burro (vang), adriças, escotas, catracas (winches), balaústres e guarda-mancebos, púlpito; vela grande (com rizos marcados) e genoa como superfícies curvas (bolsas), birutas. Anatomia: rótulos clicáveis (CSS2DRenderer) com nome em PT-BR (+inglês se intl), uma frase de função e lista de partes navegável; destacar a parte ao selecionar. Controles: girar/zoom (OrbitControls), direção do vento verdadeiro (slider) — o barco aproa e as velas caçam/folgam e mudam de bordo coerentemente, banda (adernamento) conforme força do vento, rizar a grande (1º/2º rizo), enrolar a genoa (%), mostrar/ocultar rótulos, vista de cima/lado/proa. Mar com leve ondulação (respeite reduced-motion). Cores pelos tokens (casco claro com faixa --ink, velas brancas/creme leve sem ser creme de UI, mar --sea-*), bonito nos dois temas.
2) mareacao — SVG/canvas 2D interativo de mareação: rosa de pontos de vela (zona morta/"no vento", bolina cerrada, bolina folgada, través, largo, popa rasa) relativa ao vento verdadeiro; o aluno gira o barco (arrastar) e caça/folga a escota (slider); birutas (tell-tales) mostram fluxo correto, vela "panejando" (folgada demais) ou estolada (caçada demais) com base no ângulo de ataque ao vento APARENTE; triângulo de velocidades vento verdadeiro + vento do deslocamento (da velocidade do barco) = vento aparente, com valores em nós e graus; velocidade do barco por um modelo polar simples e plausível para um cruzeiro de 32 pés (explique que é aproximado). Desafios: "coloque o barco em través", "cace até as birutas ficarem paralelas", "por que o vento aparente fica mais à proa quando aceleramos?". Termos: orçar, arribar, caçar, folgar.
3) manobras — animações SVG passo a passo com vozes de comando em PT-BR: cambar por davante (virar por davante / tacking — "Preparar para cambar!" … "Cambando!"), jaibe/cambar em roda (jibe — "Preparar para jaibe!"…, com controle da retranca e perigo da retranca), capear (heave-to), rizar (passo a passo na grande), homem ao mar (MOB) — parada rápida (quick-stop) e manobra do oito (figure-eight), com as tarefas de cada tripulante (apontar e não perder de vista, lançar boia/MOB, apertar MOB no GPS/DSC, etc.), e fundear (escolha do local, aproximação contra o vento, filame/escopo com faixa recomendada e explicação; marque como orientação geral). Barco, vento e trajetória em vista de cima; etapas com texto; tocar/pausar/etapa a etapa; reduced-motion = só etapas.` },

  { key: 'meteo', prompt: `SEUS WIDGETS: meteo-sinotica, beaufort, quartos, provisoes.
1) meteo-sinotica — carta sinótica de superfície ESQUEMÁTICA interativa (SVG): centros de alta (A) e baixa (B) pressão com isóbaras (hPa), frentes fria (triângulos azuis), quente (semicírculos vermelhos), oclusa e estacionária com a simbologia padrão; alternar Hemisfério Sul/Norte (no Sul, ventos giram no sentido HORÁRIO em torno da baixa e anti-horário em torno da alta — confirme e explique pela força de Coriolis e lei de Buys-Ballot adaptada); o aluno clica num ponto → direção do vento (ângulo de ~15–30° cruzando as isóbaras em direção à baixa sobre o mar), intensidade relativa pelo espaçamento das isóbaras, e tendência (frente fria chegando: vento rondando, pressão caindo/subindo). Cenários típicos da costa brasileira: passagem de frente fria no Sul/Sudeste (vento rondando de NE para SW), Alta Subtropical do Atlântico Sul, alísios no Nordeste, ciclone extratropical. Modo desafio com perguntas. Indique as fontes oficiais de cartas sinóticas do Brasil (Marinha/CHM — Serviço Meteorológico Marinho) como links.
2) beaufort — escala Beaufort 0–12 (WMO): velocidade em nós, termo descritivo em PT-BR, aspecto do mar, altura provável das ondas (m), ilustração SVG animada do mar para cada força (respeite reduced-motion), e orientação GERAL de vela para um cruzeiro de 32 pés (quando considerar rizar etc., marcado como orientação geral, não regra). Slider de força + quiz.
3) quartos — planejador de quartos de serviço para travessia: tripulação 2–6 pessoas, sistemas (ex.: 3 em 6 fora; 4 em 8 fora; 2 em 4 fora em dupla; sistema sueco; quartos de "cão"), gera grade de 24 h (e de vários dias, mostrando a rotação), horas de descanso por pessoa, quem está de quarto em cada hora; dicas de segurança (colete e linha de vida à noite, regra de chamar o comandante). Exportar/imprimir a grade.
4) provisoes — calculadora de provisões e autonomia: distância (mn), velocidade média estimada (nós) e margem → dias de viagem; tripulação; água (litros/pessoa/dia com valor padrão editável e explicação de que é estimativa), comida (refeições/dia), combustível (consumo do motor em L/h editável e horas de motor previstas), gás de cozinha; resultado em tabela + checklist de itens (kit médico, pirotécnicos, peças sobressalentes, etc.). Tudo marcado como estimativa.` },

  { key: 'radio', prompt: `SEUS WIDGETS: vhf-sim, alfabeto-fonetico.
1) vhf-sim — simulador de rádio VHF marítimo com DSC: face do rádio (display de canal, botões 16/9, potência alta/baixa 25 W/1 W, squelch, botão DISTRESS com tampa: levantar tampa e segurar 5 s), canais principais (16 = socorro, segurança e chamada; 70 = DSC — somente digital, nunca voz; 13 = segurança da navegação ponte-a-ponte; 6 = intership/SAR — cite a fonte ITU (Regulamento de Radiocomunicações, Apêndice 18) e marque com VL.ui.seloQ() qualquer uso específico do Brasil que você não puder verificar). Construtor de mensagens: MAYDAY (formato: MAYDAY ×3, aqui é/THIS IS + nome ×3 + indicativo/MMSI, MAYDAY + nome, posição, natureza do perigo, auxílio desejado, número de pessoas, outras informações, OVER/CÂMBIO), PAN-PAN, SÉCURITÉ, chamada de rotina e resposta/relay (MAYDAY RELAY), SEELONCE MAYDAY, SEELONCE FEENEE, alertas DSC (Distress, Urgency, Safety, Routine) e sequência correta (alerta DSC primeiro, depois voz no 16). Gera o roteiro de fala com a pronúncia; simulação de "transmissão" com resposta de uma estação costeira fictícia. Modo desafio: ordenar as partes do MAYDAY, escolher o tipo de chamada para cada situação (homem ao mar, motor parado perto das pedras, tronco à deriva...). Fonte: Regulamento de Radiocomunicações da UIT; procedimentos GMDSS (IMO).
2) alfabeto-fonetico — alfabeto fonético internacional (Alfa, Bravo, Charlie, Delta, Echo, Foxtrot, Golf, Hotel, India, Juliett, Kilo, Lima, Mike, November, Oscar, Papa, Quebec, Romeo, Sierra, Tango, Uniform, Victor, Whiskey, X-ray, Yankee, Zulu) com a pronúncia, e algarismos no padrão da UIT (Apêndice 14 do RR: NADAZERO, UNAONE, BISSOTWO, TERRATHREE, KARTEFOUR, PANTAFIVE, SOXISIX, SETTESEVEN, OKTOEIGHT, NOVENINE, DECIMAL, STOP — confirme e cite; e mencione o uso corrente simplificado). Treinos: soletrar o nome do barco/indicativo; ouvir (Web Speech API speechSynthesis se disponível, com fallback só visual) e digitar; cronômetro e placar.` },
]

phase('Construção')
const results = await parallel(JOBS.map(j => () =>
  agent(COMMON + '\n\n' + j.prompt + `\n\nRótulo da sua pasta temporária: ${j.key}. RETOMADA: uma tentativa anterior desta tarefa caiu por falha de rede antes de terminar. Se algum dos SEUS arquivos já existe em ${ROOT}/app/widgets/ ou ${ROOT}/app/assets/css/widgets/, NÃO recomece do zero: leia, teste no navegador, complete o que faltar e corrija. Reaproveite também ${SP}/w-${j.key}/ se existir. No topo de cada widget/<nome>.js, mantenha um comentário de cabeçalho documentando as opts aceitas e um exemplo de bloco de lição (outros autores leem isso). Ao terminar, devolva o manifesto estruturado (inclua os caminhos dos PNGs finais que você inspecionou).`, { label: `widget:${j.key}`, phase: 'Construção', schema: RET })))
return results.map((r, i) => r ? { key: JOBS[i].key, widgets: r.widgets.map(w => ({ nome: w.nome, exemplo: w.exemplo_bloco, opts: w.opts, limit: w.limitacoes })), core_requests: r.core_requests, notas: r.notas } : { key: JOBS[i].key, failed: true })